### ISSUE TITLE
Dependancy error `fs.rmSync is not a function`

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy-hub#1784]
Ubuntu 22.04

Clone, install and run with either:
```sh
yarn install
yarn develop
```
or
```sh
npm install
npm run develop
```

I get the same errors:

First run:

```sh
yarn run v1.22.19
$ src/build/run.mjs develop
$ src/build/preprocess.mjs preprocess --md copy --vue copy --insert copy --resource copy
Placing files into build directories.. 3.047 sec
Fixing Markdown files..                18.339 sec
Total preprocessing time:              21.391 sec
$ src/build/preprocess.mjs watch --md copy --vue copy --insert copy --resource copy &
$ gridsome develop
Gridsome v0.7.23

Initializing plugins...
/home/cameron/dev/galaxy/galaxy-hub/gridsome.server.js:608
            if (event.location?.name) {
                               ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at p._moduleCompile (/home/cameron/dev/galaxy/galaxy-hub/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/home/cameron/dev/galaxy/galaxy-hub/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at n (/home/cameron/dev/galaxy/galaxy-hub/node_modules/jiti/dist/v8cache.js:2:2472)
    at Plugins.initialize (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/lib/app/Plugins.js:45:11)
    at App.init (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/lib/app/App.js:120:18)
    at App.bootstrap (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/lib/app/App.js:49:16)
    at module.exports (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/lib/app/index.js:12:18)
    at module.exports (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/lib/develop.js:20:21)
    at /home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/index.js:44:12
    at Command.<anonymous> (/home/cameron/dev/galaxy/galaxy-hub/node_modules/gridsome/index.js:13:44)
    at Command.listener (/home/cameron/dev/galaxy/galaxy-hub/node_modules/@gridsome/cli/node_modules/commander/index.js:315:8)
```

Subsequent runs:

```sh
yarn run v1.22.19
$ src/build/run.mjs develop
$ src/build/preprocess.mjs preprocess --md copy --vue copy --insert copy --resource copy
Placing files into build directories.. file:///home/cameron/dev/galaxy/galaxy-hub/src/build/preprocess.mjs:190
                fs.rmSync(dirPath, { recursive: true });
                   ^

TypeError: fs.rmSync is not a function
    at setupBuildDirs (file:///home/cameron/dev/galaxy/galaxy-hub/src/build/preprocess.mjs:190:20)
    at doPrePartitioning (file:///home/cameron/dev/galaxy/galaxy-hub/src/build/preprocess.mjs:180:5)
    at Command.main (file:///home/cameron/dev/galaxy/galaxy-hub/src/build/preprocess.mjs:113:9)
    at Command.listener [as _actionHandler] (/home/cameron/dev/galaxy/galaxy-hub/node_modules/commander/lib/command.js:488:17)
    at /home/cameron/dev/galaxy/galaxy-hub/node_modules/commander/lib/command.js:1207:65
    at Command._chainOrCall (/home/cameron/dev/galaxy/galaxy-hub/node_modules/commander/lib/command.js:1124:12)
    at Command._parseCommand (/home/cameron/dev/galaxy/galaxy-hub/node_modules/commander/lib/command.js:1207:27)
    at Command.parse (/home/cameron/dev/galaxy/galaxy-hub/node_modules/commander/lib/command.js:878:10)
    at file:///home/cameron/dev/galaxy/galaxy-hub/src/build/preprocess.mjs:60:13
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
src/build/preprocess.mjs preprocess --md copy --vue copy --insert copy --resource copy exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Anyone else getting this on a fresh clone?

**Comment by dannon** [comment]
I've never seen this one before. What version of node is this?

**Comment by neoformit** [comment]
Ahh... it's a new, fresh node/yarn!

```
$ node -v
v12.22.9

$ yarn -v
1.22.19
```

**Comment by dannon** [comment]
If you update to 16+ it'll definitely work.  I will set an engine spec so there's a better warning here.

Maybe helpful info - I use and recommend nvm for managing multiple node versions and it's super handy.

**Comment by dannon** [comment]
#1785 adds a minimum viable engine requirement to package.json -- if you try to run with something that's incompatible you'll now get something like:
```
error galaxy-hub@: The engine "node" is incompatible with this module. Expected version ">=14.14". Got "12.22.10"
```

which should be a better clue.  Thanks for the report!
