### ISSUE TITLE
Unable to install Galaxy locally on windows even after installing ubuntu subsytem

### ISSUE THREAD

**Issue by abhilash719** [galaxyproject/galaxy-hub#607]
I am getting the following error

```
ERROR: Command errored out with exit status 1:
     command: /home/abhilash719/galaxy/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rk_xp25_/pysam/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rk_xp25_/pysam/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rk_xp25_/pysam/pip-egg-info
         cwd: /tmp/pip-install-rk_xp25_/pysam/
    Complete output (130 lines):
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -E
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for C compiler warning flags... -Wall
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -E
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... no
    checking for BZ2_bzBuffToBuffCompress in -lbz2... no
    configure: error: libbzip2 development files not found

    The CRAM format may use bzip2 compression, which is implemented in HTSlib
    by using compression routines from libbzip2 <http://www.bzip.org/>.

    Building HTSlib requires libbzip2 development files to be installed on the
    build machine; you may need to ensure a package such as libbz2-dev (on Debian
    or Ubuntu Linux) or bzip2-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

    Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    config.mk:2: *** Resolve configure error first.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rk_xp25_/pysam/setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-install-rk_xp25_/pysam/setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tnabtaf** [comment]
@abhilash719 I am closing this issue.  **And I apologize for taking almost a month to see it.**  If you are still having this or other issues, please post them at https://help.galaxyproject.org/
